### ISSUE TITLE
Fullscreen issue

### ISSUE THREAD

**Issue by Distractic** [qwbarch/lc-auto-start#2] opened 2024-01-12 07:41 UTC
I'm playing with **Display mode** to `Window` when I need to debug with several game instances. 
But when the LAN scene starts, the **Display mode** is changed to `Fullscreen` (or the resolution is enlarged to the screen resolution)

**Comment by qwbarch** [comment] 2024-01-12 11:18
I'm not able to reproduce this issue. Does this happen when you're only using ``AutoStart``?

**Comment by Distractic** [comment] 2024-01-12 17:11
> I'm not able to reproduce this issue. Does this happen when you're only using `AutoStart`?

Exactly. I'm these settings (image):
![image](https://github.com/qwbarch/lc-auto-start/assets/46402441/91ba23b7-b7f7-49b0-8be3-974cc2a0741b)

I removed the mod and restarted the game, my resolution was kept.

However, when I'm using the mod, when I have this menu (image), the resolution is changed to be the same than my entire screen:
![image](https://github.com/qwbarch/lc-auto-start/assets/46402441/401c4167-0689-484d-8396-6189a4084096)

**Comment by qwbarch** [comment] 2024-01-12 23:13
That's incredibly odd, I can't replicate it at all. My window stays the same resolution (small windowed) the whole way 😅

**Comment by qwbarch** [comment] 2024-01-14 06:43
Turns out this is from lethal company's newest update. I was still on the previous version until now so I never ran into it.
I'll have to look into this later though since I'm prioritizing a different mod for now

**Comment by qwbarch** [comment] 2024-01-28 05:39
Fixed in the latest release: https://thunderstore.io/c/lethal-company/p/qwbarch/AutoStart/

**Closed as completed by qwbarch** 2024-01-28 05:39 UTC
Labels: bug
